### ISSUE TITLE
Add Puppet Strings compatible documentation

### ISSUE THREAD

**Issue by Hexoplon** [martinaamodt/cockroachdb#19]
Each class and defined type must include documentation at the top of the file that describes the purpose of the class or defined type, as a minimum, in a format that Puppet Strings can interpret.

[best practice](https://github.com/puppetlabs/best-practices/blob/master/puppet-module-design.md#module-design)

**Comment by martinaamodt** [comment]
Add default values if set, in the documentation in init.pp
