### ISSUE TITLE
Implement locality key value pairs as array and iterate in template

### ISSUE THREAD

**Issue by Hexoplon** [martinaamodt/cockroachdb#60]

**Comment by martinaamodt** [comment]
https://puppet.com/docs/puppet/latest/lang_expressions.html
 https://puppet.com/docs/puppet/latest/lang_functions.html

**Comment by martinaamodt** [comment]
Lager array med parametere:
`<% $options = [
    $region,
    $datacenter,
    $zone,
  ]
%> `
Etter ifstatment for secure kommer vi hit:
`ExecStart = /usr/local/bin/cockroach start --insecure <% if $options.each |$option| { $option != undef } { -%>--locality=<% $options.each |$option| { "$option," } -%> <% } -%> --advertise-addr=<%= $facts[hostname] %> --join=<%= $node1ip %>,<%= $node2ip %>,<%= $node3ip %> --cache=<%= $cache %> --max-sql-memory=<%= $maxsqlmemory %> `

Usikker på om if i execStart funker. Men det store "problemet" er i --locality hvor jeg da setter $option, hvordan skal man da få lagt inn om det faktisk er en zone eller region eller datacenter, etc. 
Noen tanker? @Hexoplon @joachiwi
