### ISSUE TITLE
Fix 'The use of `eval` is a serious security risk.' issue in Gemfile

### ISSUE THREAD

**Issue by martinaamodt** [martinaamodt/cockroachdb#65]
[CodeFactor](https://www.codefactor.io/repository/github/martinaamodt/cockroachdb/overview/dev) found an issue: The use of `eval` is a serious security risk.

It's currently on:
[Gemfile:69
](https://www.codefactor.io/repository/github/martinaamodt/cockroachdb/source/dev/Gemfile#L69)

**Comment by martinaamodt** [comment]
@Hexoplon Tuklet noe med gemfile? :smile_cat:

**Comment by Hexoplon** [comment]
> @Hexoplon Tuklet noe med gemfile?

Nope :P

**Comment by Hexoplon** [comment]
Created in default PDK template, not used for anything but development.
